# Codecov configuration for Claude Unity Bridge
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        informational: false
    patch:
      default:
        target: auto
        threshold: 5%
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

flags:
  python-skill:
    paths:
      - skill/src/
    carryforward: true
